"""make user fields optional

Revision ID: 46966f4168d5
Revises: d2c48952a8e3
Create Date: 2025-05-28 13:40:46.274533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46966f4168d5'
down_revision: Union[str, None] = 'd2c48952a8e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'bio',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_user_user_name'), table_name='user')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'birth_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('birth_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_user_user_name'), 'user', ['user_name'], unique=True)
    op.alter_column('user', 'bio',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
