"""Add new user fields

Revision ID: c2c48952a8e2
Revises: e2860befcdc0
Create Date: 2025-05-13 06:28:48.337835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2c48952a8e2'
down_revision: Union[str, None] = 'e2860befcdc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('user', sa.Column('user_name', sa.String(), nullable=True))
    op.add_column('user', sa.Column('birth_date', sa.DateTime(), nullable=True))
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_user_user_name'), 'user', ['user_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_user_name'), table_name='user')
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user', 'birth_date')
    op.drop_column('user', 'user_name')
    op.drop_column('user', 'last_name')
    # ### end Alembic commands ###
